### PR TITLE
feat: redesign

### PR DESCRIPTION
**Pull request by mzanoni**
https://trello.com/c/D1413HmU

### CODE REVIEW

**Comment by CBE-RELEWISE** [comment]
Created a new issue [User not correctly indentified for P13N #49](https://github.com/Relewise/relewise-demos-shop-vue/issues/49) in GitHub

**Comment by CBE-RELEWISE** [comment]
Created a new issue [On Sale tags has different colors in recommendations and search results.  #50](https://github.com/Relewise/relewise-demos-shop-vue/issues/50) in GitHub

**Comment by CBE-RELEWISE** [comment]
Created a new issue [Frontpage can scroll "right/left" #51](https://github.com/Relewise/relewise-demos-shop-vue/issues/51) in GitHub

**Review by brianhdk — APPROVED** [review]
Awesome work, MZA! #yourock!

**Pull request merged**
